### PR TITLE
add usage text and --help command

### PR DESCRIPTION
**Pull request by adnelson**
A small improvement. Using an argument parsing library like `clap` would be even better but initial steps :)

### CODE REVIEW

**Comment by KillingSpark** [comment]
Hey, thanks for this! Could you change the line 265 `std::process::exit(1);` to something similar to `unrecoverable_error(format!("Unknown cli arg: {}", unknown));`?

The unrecoverable error panics for a normal process but if it is PID1 it drops the user into a shell so they can remedy any errors they made, which is impossible if rustysd just exits :)

I am not a huge fan of clap and friends, they feel too heavy for just a few cli args, but you are right cli args parsing could/should be done by some external lib.

**Comment by adnelson** [comment]
sorry for the slow response -- done

**Comment by MggMuggins** [comment]
[pico-args](https://crates.io/crates/pico-args) got dropped in the redox dev channel a couple of weeks ago, it's a barebones type of library, might be what you're looking for. If I get time this weekend I could see what I can do.

**Comment by KillingSpark** [comment]
pico-args looks awesome! That's pretty much the level of help I want from a arg parsing lib. If you have the time and could make a PR with it I would be super glad. Else I will probably use it when I get to rewriting arg parsing :)

**Comment by KillingSpark** [comment]
I just saw your PR. Thank you :)

**Pull request merged**
